### ISSUE TITLE
subdomain support

### ISSUE THREAD

**Issue by Hootie81** [mooltipass/android_companion#10]
When using autofill in duckduckgo the autofill query to the MP includes the "www." of the address. as the stored credentials dont contain this for ease of searching on the device it ultimately results in 'no credentials found' and the autofill closing 

from memory something similar happens on a pc, but it removes the first part of the address then tries again
eg for website first.second.tld it tries the full address first, if exists asks for approval. if denied or doesnt exist then tries second.tld

MP Bundle 7
App ver 1.1-se

**Comment by limpkin** [comment]
@mathfactory following my message, I suggest that we:
- strip the www in any case (as moolticute does)
- if we have time, use the [public suffix list](https://publicsuffix.org/) to extract the domain.tld and subdomain.domain.tld
- in mooltifill (like in moolticute), offer the choice to enable or disable subdomain support: when enabled, mooltifill can try subdomain.domain.tld on recall, and if it fails, use domain.tld

**Comment by limpkin** [comment]
i'll leave this ticket open for when we implement the public suffix list and subdomain support :)

**Comment by limpkin** [comment]
PSL was implemented and released! :)
