### ISSUE TITLE
App reports "device without communication service found, please update device" with firmware bundles 4 and 8.

### ISSUE THREAD

**Issue by Freakus** [mooltipass/android_companion#16]
App reports "device without communication service found, please update device" with firmware bundles 4 and 8 when selecting the "Test Mooltipass Device Communication" option.

No passwords are being auto-filled.

I initially tried last night, with firmware bundle 4 - after receiving the aforementioned message I let my device charge overnight, installed the latest bundle available to me (8) and tried again this morning. I have forced a reboot of the Mooltipass Mini BLE as well as restarted my phone to no avail.

Phone information:
Redmi Note 10 5G
MIUI Global 12.5.4 Stable - (12.5.4.0(RKSEUXM)
Android version: 11 RP1A.200720.011
Android security update: 2022-01-01

**Comment by limpkin** [comment]
Hello!
You'll need to unpair and pair again :)

**Comment by Freakus** [comment]
Should have thought of that one, sorry! This is what happens when I try to do things just before bed/when first waking up!

That's resolved the test issue, though it's still not autofilling passwords in chrome or other apps even though I have the autofill service selected. I'm suspecting I might have a setting misconfigured somewhere else but I'm out of ideas of where to look.

Thankyou for all your assistance so far, and thankyou for a wonderful product.

**Comment by limpkin** [comment]
No no, we should change the information message to mention the needed unpairing/pairing :)
So it seems it won't work on chrome as it is actively blocking the autofill framework... could you try firefox?
thanks for the kind words!

**Comment by Freakus** [comment]
Firefox is working with the app nicely!

I'm guessing for other apps to work reliably with this we're waiting on #9 ?

**Comment by limpkin** [comment]
that's correct! but in some cases you may get lucky...

**Comment by Freakus** [comment]
Fantastic! Thankyou for all your help.

I'm happy to close this unless you want to keep it open for the issues with Chrome?

**Comment by limpkin** [comment]
let's close it then :), i'll create a separate one for chrome :)

**Comment by limpkin** [comment]
@Freakus i just pushed an update for chrome on mooltifill, could you check that you have version 1.5-se and try if it works on chrome for you? :)

**Comment by Freakus** [comment]
@limpkin Not sure what version I have now, but it just updated and is working!

Thankyou very much!

**Comment by limpkin** [comment]
that is awesome :)
