### ISSUE TITLE
Firmware confusion

### ISSUE THREAD

**Issue by RChadwick7** [mooltipass/android_companion#19]
I have two Mini BLE's. One I upgraded to official bundle 8. The other I upgraded to Beta bundle 8 to get Android working. When I try to upgrade my first unit to bundle 8, it gives an error, as I'm trying to upgrade 8 to 8.

**Comment by limpkin** [comment]
Hello!
I'm confused... themooltipass.com/updates currently offer bundle v7 while beta-updates.themooltipass.com offers bundle v8.
I'm not sure what you mean by official & beta bundle versions :)

**Comment by RChadwick7** [comment]
I suppose I could have accidentally upgraded my other BLE to 8 Beta. If so, I have one that is recognized by the app, and one that is not. knowing 7 is the official latest, what should I try to get the app to recognize my other BLE?

**Comment by limpkin** [comment]
could you unpair & repair? :)

**Comment by RChadwick7** [comment]
I unpaired ad repaired, and the android app will connect to it fine. Now I just need the Android app working :)

**Comment by limpkin** [comment]
> I unpaired ad repaired, and the android app will connect to it fine. Now I just need the Android app working :)

I'm not sure to follow you...

**Comment by RChadwick7** [comment]
Sorry, was referring to the other issue I was having. Seems this was all my mistake, caused from my wrong belief that there as an official 8 and a beta 8. Unpairing and repairing the unit that wasn't connecting to the app now connects fine.
