### ISSUE TITLE
Mooltifill not filling on Samsung Fold3

### ISSUE THREAD

**Issue by GuardianZX9** [mooltipass/android_companion#22]
Mooltifill is set as the default autofill app.

I am only able to fill the example shown to my GitHub account in Chrome.

No other apps or websites will fill, nothing app even shows the fill icons.

**Comment by limpkin** [comment]
hello!

could you double check that the other websites you tried mooltifill on were not using subdomains, as we don't support that feature yet? :)

**Comment by GuardianZX9** [comment]
Yes, no subdomains.

**Comment by limpkin** [comment]
that's baffling... could you share with me a domain we could use to replicate the issue?

**Comment by GuardianZX9** [comment]
pncbank.com

Maybe I am doing something incorrectly. MooltiPass is on, Bluetooth enabled MooltiFill is running, open mooltifill and click Test MP device connection(doesn't always automatically connect to MP)   Open Chrome, navigate to pncbank.com, click sign on.  click in both the username and password fields and nothing happens.    Same happens with the PNC android application.

**Comment by limpkin** [comment]
thanks for the example! do you have another one not bank related? in our experience they sometimes prevent such autofill mechanisms :)

**Comment by GuardianZX9** [comment]
Tried multiple sites, none will fill including github.
I can choose favorites and manually enter site credentials with the MP.

**Comment by limpkin** [comment]
so github worked before but not anymore?

**Comment by GuardianZX9** [comment]
Correct.   I can see Android System detects a "hardware" keyboard.   but I never get the MooltiFill popup inside the credential field like I used to.    I will test another android phone.

**Comment by limpkin** [comment]
could you also try with another browser?

**Comment by limpkin** [comment]
@GuardianZX9 could you try our latest release?

**Comment by jtgans** [comment]
Confirming the same problem on a Microsoft Surface Duo. I'm running Bromite (Chrome) with Mooltifill installed. Connection test succeeds, but no popups for github.com or any other site I've tested (without subdomains). I can manually login using the minible, but popups never work.

Would ADB logs help here? I'd be happy to pull one and attach.

**Comment by limpkin** [comment]
@jtgans could you check if you get the same issue with firefox?

**Comment by jtgans** [comment]
I'll see if I can do so. I suspect the same results will occur -- when I choose autofill from the context menu, nothing shows up in the logs, either.

**Comment by jtgans** [comment]
Okay, so putting Firefox Nightly on my Duo brings up the dialog properly. Now I'm having all sorts of BLE issues, which is unrelated. So I'm wondering maybe if this is a non-Firefox issue. Perhaps the client apps aren't working right?

**Comment by jtgans** [comment]
Okay, so logs are pretty worthless because the "Autofill" menu I'm talking about is not for triggering the Android autofill service. There's some kind of interaction going on between Mooltifill and Bromite that causes Bromite to not work with Mooltifill. Supposedly Bromite supports the Android autofill framework, according to https://github.com/bromite/bromite/issues/547, so this (in theory) should work.

**Comment by jtgans** [comment]
Also, FWIW, I'm using Bromite 101.0.4952.53, which is the latest, so it should definitely support the Autofill service.

**Comment by mathfactory** [comment]
I guess for Bromite we need to add this to the known browsers list in app/src/main/res/xml-v28/autofill_service.xml. If you want you can try it with the following addition there (cf. also #18 where we added the known browsers list) and build yourself, otherwise I can add a PR for it:

<compatibility-package
            android:name="org.bromite.bromite"
            android:maxLongVersionCode="10000000000"/>

**Comment by mathfactory** [comment]
` <compatibility-package
            android:name="org.bromite.bromite"
            android:maxLongVersionCode="10000000000"/>`

**Comment by jtgans** [comment]
Oho! Okay, lemme try blowing a build with that patch and see if that helps. Wasn't aware it was a double whitelist on both sides. Crazy.

**Comment by jtgans** [comment]
Which install target do I use to test this out with? The Mathfactory one? Gradle's not exactly self-explanatory. O.o

**Comment by mathfactory** [comment]
You can use either of the targets, the only difference (currently) is the application id it generates for the apk. Only be aware that if you have installed mooltifill already you should use the same application id to not have two versions of mooltifill installed at the same time (or delete the currently installed). The "product flavors" with the corresponding application ids are defined in app/build.gradle.

**Comment by jtgans** [comment]
Yeah. Okay, well, after doing that patch, I don't see any difference. I'm sure it's part of the issue, though. Need to dig more. For completeness, the patch I stuck in there was:

```diff
diff --git a/app/src/main/res/xml-v28/autofill_service.xml b/app/src/main/res/xml-v28/autofill_service.xml
index 43b7477..885f158 100644
--- a/app/src/main/res/xml-v28/autofill_service.xml
+++ b/app/src/main/res/xml-v28/autofill_service.xml
@@ -66,4 +66,7 @@ Settings Activity. This is pointed to in the service's meta-data in the applicat
     <compatibility-package
             android:name="org.mozilla.firefox_beta"
             android:maxLongVersionCode="10000000000"/>
-</autofill-service>
\ No newline at end of file
+    <compatibility-package
+            android:name="org.bromite.bromite"
+            android:maxLongVersionCode="10000000000"/>
+</autofill-service>
```

**Comment by jtgans** [comment]
For reference, the KeePassDX guys also include this line: https://github.com/Kunzisoft/KeePassDX/blob/0d91f07646a4caa631c29d1a0167267be0088e4d/app/src/main/res/xml/dataset_service.xml#L203

**Comment by jtgans** [comment]
#29 includes this patch.

**Comment by jtgans** [comment]
Iiinterestingly, I'm seeing `onFillRequest()` calls now, but the fields aren't being populated, and the popup isn't coming up:

```
05-12 11:16:44.113  5106  5106 D MooltifillService: onFillRequest()
05-12 11:16:44.116  5106  5106 V MooltifillService: Setting hint 'username' on 1073741973:2@878696734
05-12 11:16:44.117  5106  5106 V MooltifillService: Setting hint 'password' on 1073741973:3@878696734
05-12 11:16:44.120  5106  5106 D MooltifillService: autofillable fields:{username=(1073741973:2@878696734, null), password=(1073741973:3@878696734, null)}
05-12 11:16:57.220  5106  5106 D MooltifillService: onFillRequest()
05-12 11:16:57.224  5106  5106 V MooltifillService: Setting hint 'username' on 1073741973:2@1777758687
05-12 11:16:57.224  5106  5106 V MooltifillService: Setting hint 'password' on 1073741973:3@1777758687
05-12 11:16:57.225  5106  5106 D MooltifillService: autofillable fields:{username=(1073741973:2@1777758687, null), password=(1073741973:3@1777758687, null)}
05-12 11:25:33.069  5106  5106 D MooltifillService: onFillRequest()
05-12 11:25:33.074  5106  5106 V MooltifillService: Setting hint 'username' on 0:65536@769962564
05-12 11:25:33.074  5106  5106 V MooltifillService: Setting hint 'current-password' on 0:65537@769962564
05-12 11:25:33.074  5106  5106 D MooltifillService: autofillable fields:{username=(0:65536@769962564, null), current-password=(0:65537@769962564, null)}
05-12 11:26:31.113  5106  5106 D MooltifillService: onFillRequest()
05-12 11:26:31.121  5106  5106 V MooltifillService: Setting hint 'username' on 0:65536@1525943665
05-12 11:26:31.121  5106  5106 V MooltifillService: Setting hint 'current-password' on 0:65537@1525943665
05-12 11:26:31.121  5106  5106 D MooltifillService: autofillable fields:{username=(0:65536@1525943665, null), current-password=(0:65537@1525943665, null)}
05-12 11:27:03.799  5106  5106 D MooltifillService: onFillRequest()
05-12 11:27:03.805  5106  5106 V MooltifillService: Setting hint 'username' on 0:65536@594788718
05-12 11:27:03.805  5106  5106 V MooltifillService: Setting hint 'current-password' on 0:65537@594788718
05-12 11:27:03.805  5106  5106 D MooltifillService: autofillable fields:{username=(0:65536@594788718, null), current-password=(0:65537@594788718, null)}
05-12 12:25:39.627  5106  5106 D MooltifillService: onFillRequest()
05-12 12:25:39.633  5106  5106 V MooltifillService: Setting hint 'username' on 1:65536@448295863
05-12 12:25:39.633  5106  5106 V MooltifillService: Setting hint 'current-password' on 1:65537@448295863
05-12 12:25:39.633  5106  5106 D MooltifillService: autofillable fields:{username=(1:65536@448295863, null), current-password=(1:65537@448295863, null)}
05-12 13:20:39.236  1192  1425 I ActivityManager: Start proc 6662:ch.stephanelectronics.mooltifill/u0a331 for service {ch.stephanelectronics.mooltifill/de.mathfactory.mooltifill.MooltifillService}
05-12 13:20:45.877  1192 11837 I AutofillManagerServiceImpl: disableOwnedServices(10331): AutofillServiceInfo[ServiceInfo{4f6bd76 de.mathfactory.mooltifill.MooltifillService}, settings:de.mathfactory.mooltifill.SettingsActivity, hasCompatPckgs:true], inline suggestions enabled:false
```

**Comment by jtgans** [comment]
Aha! So, apparently the username and password are empty? That's surprising -- I do have credentials in the Mooltipass for github.com:

```
05-12 14:12:33.452  8276  8276 D MooltifillService: Query is: github.com
05-12 14:12:33.452  8276  8276 D MooltifillService: No username or password associated with this query.
```

**Comment by jtgans** [comment]
So, uh, how does `MooltifillService` actually make the request to the Mooltipass? The function `getInfo` doesn't seem to actually make a request to the device at all?

**Comment by jtgans** [comment]
Weird. I'm not seeing a call to `MooltifillActivity$getCredentials` at all.

```
05-12 15:27:59.700 10436 10466 D Mooltifill: connect() entered
05-12 15:27:59.723 10436 10436 D Mooltifill: onStartCommand
05-12 15:28:03.819  1192  1225 I AutofillManagerServiceImpl: disableOwnedServices(10331): AutofillServiceInfo[ServiceInfo{d8799e1 de.mathfactory.mooltifill.MooltifillService}, settings:de.mathfactory.mooltifill.SettingsActivity, hasCompatPckgs:true], inline suggestions enabled:false
05-12 15:28:04.721 10436 10436 D Mooltifill: enableService(): intent=Intent { act=android.settings.REQUEST_SET_AUTOFILL_SERVICE dat=package:de.mathfactory.mooltifill }
05-12 15:28:07.646 10436 10436 D Mooltifill: onDefaultServiceSet() resultCode=ActivityResult{resultCode=RESULT_CANCELED, data=null}
05-12 15:28:23.078 10436 10436 D MooltifillService: onFillRequest()
05-12 15:28:23.126 10436 10436 D MooltifillService: Have 1 nodes
05-12 15:28:23.126 10436 10436 D MooltifillService: Filling with {}
05-12 15:28:23.126 10436 10436 V MooltifillService: Setting hint 'username' on 0:65536@1691739917
05-12 15:28:23.127 10436 10436 V MooltifillService: Setting hint 'current-password' on 0:65537@1691739917
05-12 15:28:23.127 10436 10436 D MooltifillService: autofillable fields:{username=(0:65536@1691739917, null), current-password=(0:65537@1691739917, null)}
05-12 15:28:23.128 10436 10436 D MooltifillService: isWebDomain
05-12 15:28:23.128 10436 10436 D MooltifillService: Query is: github.com
05-12 15:28:23.128 10436 10436 D MooltifillService: Info to fill is {username=(0:65536@1691739917, null), current-password=(0:65537@1691739917, null)}
05-12 15:28:23.128 10436 10436 D MooltifillService: No username or password associated with this query.
05-12 15:28:23.176 10436 10436 D Mooltifill: onStartCommand
05-12 15:28:29.726 10436 10460 D Mooltifill: onConnectionStateChange 133 0
05-12 15:28:29.734 10436 10467 D Mooltifill: awaitClose
05-12 15:28:29.735 10436 10467 D Mooltifill: disconnect()
05-12 15:28:29.746 10436 10466 D Mooltifill: connect() finished
05-12 15:28:29.754 10436 10436 D Mooltifill: Aware: Disconnected
```

**Comment by mathfactory** [comment]
MooltifillService doesn't (nor getInfo()) actually make a request to the Mooltipass. It "only" assembles autofill (meta) information and displays a button near the login field in the browser / app. After the user presses the button the actual request is made to the mooltipass device in MooltifillActivity. Do you see the button in the login form? The button should be shown after callback.onSuccess(response.build()) has been called in onFillRequest().

**Comment by jtgans** [comment]
No, no button is present at all.

**Comment by jtgans** [comment]
There's a block of code at https://github.com/mooltipass/android_companion/blob/86e1fb18926614a231ef87ee2316d6c074b65192/app/src/main/java/de/mathfactory/mooltifill/MooltifillService.kt#L81 that checks to see if there's a username or password in the info that calls `onSuccess(null)`, which according to the docs blocks the rest of the process.

So maybe I'm barking up the wrong tree here: it seems like we're filtering for the wrong data in the metadata that is sent to onFill Request, then.

**Comment by jtgans** [comment]
Aha! It's not the username bit that's failing. It's the password. Somehow it's being treated as "current-password". This is on the main github.com/login page. Wacky.

**Comment by jtgans** [comment]
Okay, so github apparently gives their password field the attribute `autocomplete="current-password"`. If we're just looking for `View.AUTOFILL_HINT_PASSWORD` in the structure, we'll miss it, which explains why I can't test with Github anymore. :P

KeePassDX, in contrast, has a really crazy convoluted thing to iterate through the list of autofillable fields to find the username and password hints here: https://github.com/Kunzisoft/KeePassDX/blob/d7decba3f5555c60532c83b69f0a7b58712e3f40/app/src/main/java/com/kunzisoft/keepass/autofill/StructureParser.kt#L142

**Comment by jtgans** [comment]
Okay, so I have a patch to make this work. It involved changing the way `MooltifillService$getHint` functions. It's a bit nasty how we're inferring this stuff, so I might consider rewriting it in another PR later if it bites me again. :P

**Comment by mathfactory** [comment]
A hint like "current-password" should be fine as there is a heuristic in inferHint(), which maps it to View.AUTOFILL_HINT_PASSWORD. I found a case where this could fail though: Maybe you could replace the line 185 in the MooltifillService

`node.autofillHints?.firstOrNull()?.let { return it }`

with

`node.autofillHints?.firstOrNull()?.let(this::inferHint)?.let { return it }`

and check whether this helps?

**Comment by jtgans** [comment]
The problem is that the hint was pre-filled, so the code in `getHint` just passed it on down the call chain as "current-password".

**Comment by mathfactory** [comment]
Yep, that's why I want to run inferHint() on it

**Comment by mathfactory** [comment]
Ah, looks like we have found the same solution at the same time. :) Thanks for the PR, I'll give some feedback there.

**Comment by jtgans** [comment]
Ah, also, @GuardianZX9, the reason why you can't get Mooltifill to work on pncbank.com is because their password field is set to "autocomplete='off'" which prevent autofill from occurring. It's possible PNC has the same policy for their app, or their app is constructed in such a way that the heuristics can't find the field.

I have a similar problem with r.bank -- they even go so far as to disable right clicking on the whole webpage. Banks are silly. :P

**Comment by limpkin** [comment]
1.8 is currently being released!
Thanks a lot guys :)
