### ISSUE TITLE
"Device without communication service found, please update device"

### ISSUE THREAD

**Issue by hijackeel** [mooltipass/android_companion#34]
When trying to run the app's "Functionality Test", I get the message "Device without communication service found, please update device". My Mooltipass is on bundle 8. I've removed a different pairing from another Mooltipass, so mine is the only one, and I've tried unpairing and repairing my Mooltipass with my phone.

**Comment by limpkin** [comment]
Wow that's a first, the message usually goes away after updating the device and reinitiliazing the pairing. could you reboot your phone as well?

**Comment by hijackeel** [comment]
I deleted pairings from both the Mooltipass and the phone, restarted the phone, paired them, and it works. Thanks!
